import React, { useRef } from "react";
import styles from "../styles/components/AppLayout.module.scss";
import Head from "next/head";
import favicon from '../public/images/favicon.png'

const AppLayout = ({ children }) => {
	console.log(favicon)
	return (
		<>
			<div className={styles.container}>
				<Head>
					<title>Naša svadba</title>
					<meta name="description" content="Generated by create next app" />
					<meta charset="UTF-8" />
					<meta name="viewport" content="width=device-width, initial-scale=1.0" />
					<link rel="icon" href={favicon.src} type="image/png" sizes="16x16" />
					<link rel="preconnect" href="https://fonts.googleapis.com" />
					<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
					<link
						href="https://fonts.googleapis.com/css2?family=Cedarville+Cursive&family=Reenie+Beanie&family=Shalimar&display=swap&subset=latin,latin-ext,cyrillic"
						rel="stylesheet"
					/>
				</Head>

				<main className={styles.main}>{children}</main>
			</div>
		</>
	);
};

export default AppLayout;
