import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Homepage from "../components/homepage";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Naša svadba</title>
				<meta name="description" content="Generated by create next app" />
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link href="https://fonts.googleapis.com/css2?family=Cedarville+Cursive&family=Reenie+Beanie&family=Shalimar&display=swap&subset=latin,latin-ext,cyrillic" rel="stylesheet"/>
			</Head>

			<main className={styles.main}>
				<Homepage />
			</main>
		</div>
	);
}
